
---
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    platform: h2
    username: sa
    password:
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.H2Dialect



---
spring:
  profiles: CDC

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://DSDV-INFC-1601\QSRV1;databaseName=EIP_DAAS;trustServerCertificate=true
    platform: SQLSERVER
    username: DAAS_DEV
    password: E%7%M7$+Jit~uw%e_9Wi%xf5
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: create
        dialect: org.hibernate.dialect.SQLServerDialect


